# Generated by Django 3.1.7 on 2021-03-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='enuinciado',
            new_name='enunciado',
        ),
    ]
